#!/bin/bash
usage() {
  echo "This script doesn't accept parameters"
  echo "Usage example: $0"
  exit 1
}

print_header() {
  clear
  print_separator
  echo "#####     Yu-Gi-Oh! Card Database     #####"
  print_separator
  echo "###  Creator: kuroi kenryu              ###"
  print_separator
}

print_option() {
  echo "## $1) $2"
}

print_separator() {
  echo "###########################################"
}

main_menu() {
  print_header
  print_option 1 "Search Card"
  print_option 0 "Quit"
  print_separator
}

search_card_menu() {
  print_header
  print_option 1 "Filter by Name"
  print_option 2 "Filter by Type"
  print_option 3 "Filter by ID"
  print_option 4 "Filter by Level"
  print_option 5 "Filter by Attack"
  print_option 6 "Filter by Defense"
  print_option 7 "Filter by Attribute"
  print_option 0 "Back"
  print_separator
}

card_filter_name() {
  print_header
  echo "Enter the name of the card:"
}

card_filter_results() {
  print_header
  print_option 0 "Back"
  print_separator
}

filter_monsters_name() {
  if [ -e $monster_file ]; then
    echo $( grep -i "^.*;.*;$1;.*;.*;.*;.*;.*;.*;.*$" $monster_file )
  else
    echo "$monster_file doesn't exist" >&2
    echo ""
  fi
}

filter_magics_name() {
  if [ -e $magic_file ]; then
    echo $( grep -i "^.*;.*;$1;.*;.*;.*;.*;.*;.*;.*$" $magic_file )
  else
    echo "$magic_file doesn't exist" >&2
    echo ""
  fi
}

filter_traps_name() {
  if [ -e $trap_file ]; then
    echo $( grep -i "^.*;.*;$1;.*;.*;.*;.*;.*;.*;.*$" $trap_file )
  else
    echo "$trap_file doesn't exist" >&2
    echo ""
  fi
}

read_option() {
  echo -e "\nEnter option number: " >&2
  read option
  echo $option
}

## Check correct command usage
if [ $# != 0 ]; then
  usage
fi

###################
##   Main Loop   ##
###################
data_dir="data/"
monster_data="monster_cards.dat"
magic_data="magic_cards.dat"
trap_data="trap_cards.dat"
monster_file=$data_dir$monster_data
magic_file=$data_dir$magic_data
trap_file=$data_dir$trap_data
option=999
## Main Menu
while [ "$option" != "0" ]; do
  main_menu
  option=$( read_option )
  s1_option=999
  if [ "$option" == "1" ]; then
    ## Submenu 1
    while [ "$s1_option" != "0" ]; do 
      search_card_menu
      s1_option=$( read_option )
      s2_option=999
      ## Submenu 2
      if [ "$s1_option" == 1 ]; then
	while [ "$s2_option" != "0" ]; do
	  card_filter_name
	  read card_name
	  monster_matches=$( filter_monsters_name "$card_name" )
	  magic_matches=$( filter_magics_name "$card_name" )
	  trap_matches=$( filter_traps_name "$card_name" )
	  total_matches=$monster_matches$magic_matches$trap_matches
	  if [ "$total_matches" == "" ]; then
	    echo "No matches found for card $card_name"
	    echo "Press enter key to return to menu"
	    read enter_key
	    s2_option=0
	  else
	    read enter_key
	    #card_filter_results
	  fi
	done
      fi
    done
  fi
done
