#!/bin/bash
usage() {
  echo "This script doesn't accept parameters"
  echo "Usage example: $0"
  exit 1
}

print_header() {
  clear
  print_separator
  echo "#####     Yu-Gi-Oh! Card Database     #####"
  print_separator
  echo "###  Creator: kuroi kenryu              ###"
  print_separator
}

print_option() {
  echo "## $1) $2"
}

print_separator() {
  echo "###########################################"
}

main_menu() {
  print_header
  print_option 1 "Search Card"
  print_option 0 "Quit"
  print_separator
}

search_card_menu() {
  print_header
  print_option 1 "Filter by Name"
  print_option 2 "Filter by Type"
  print_option 3 "Filter by ID"
  print_option 4 "Filter by Level"
  print_option 5 "Filter by Attack"
  print_option 6 "Filter by Defense"
  print_option 7 "Filter by Attribute"
  print_option 0 "Back"
  print_separator
}

read_option() {
  echo -e "\nEnter option number: " >&2
  read option
  echo $option
}

## Check correct command usage
if [ $# != 0 ]; then
  usage
fi

option=999
## Main Menu
while [ "$option" != "0" ]; do
  main_menu
  option=$( read_option )
  suboption=999
  if [ "$option" == "1" ]; then
    while [ "$suboption" != 0 ]; do 
      search_card_menu
      suboption=$( read_option )
    done
  fi
done
